# This is a basic workflow to help you get started with Actions

name: build-and-push-image

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  tag: 
    outputs:
        tag: ${{ steps.tag_version.outputs.new_tag }}
    name: Tag commit
    runs-on: ubuntu-latest
    steps: 
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  frontend:
    needs: tag
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{github.actor}}/${{github.repository}}-frontend
          flavor: |
            latest=auto
          tags: |
            type=semver,pattern={{raw}},value=${{ needs.tag.outputs.tag }}
            type=sha
      - name: Set up buildx for docker
        uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
            username: ${{ github.actor }}
            password: ${{ secrets.BUILD_AND_PUSH }}
            registry: ghcr.io
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.1
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: ./images/frontend

  backend:
    needs: tag
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{github.actor}}/${{github.repository}}-backend
          flavor: |
            latest=auto
          tags: |
            type=semver,pattern={{raw}},value=${{ needs.tag.outputs.tag }}
            type=sha
      - name: Set up buildx for docker
        uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
            username: ${{ github.actor }}
            password: ${{ secrets.BUILD_AND_PUSH }}
            registry: ghcr.io
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.1
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: ./images/backend

  database:
    needs: tag
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/${{github.actor}}/${{github.repository}}-database
          flavor: |
            latest=auto
          tags: |
            type=semver,pattern={{raw}},value=${{ needs.tag.outputs.tag }}
            type=sha
      - name: Set up buildx for docker
        uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
            username: ${{ github.actor }}
            password: ${{ secrets.BUILD_AND_PUSH }}
            registry: ghcr.io
      - name: Build and push Docker images
        uses: docker/build-push-action@v2.2.1
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          context: ./images/database